language: generic 
sudo: required
services:
    -docker

before_install:
    - docker build -t reactimage/docker-react -f Dockerfile.dev .

script:
    -docker 
    - docker run reactimage/docker-react npm run test -- --coverage
